### ISSUE TITLE
Saldo da conta não atualiza

### ISSUE THREAD

**Issue by debiidebyx** [ynixt/shared-finances#3]
![image](https://user-images.githubusercontent.com/20935671/127534352-7b5dd8cc-f9e5-4940-9e6d-6330120a5274.png)

![image](https://user-images.githubusercontent.com/20935671/127534369-f5464fc6-2ad6-4560-85ff-c34199cdb135.png)

O saldo da conta não está sendo atualizado no menu de contas

**Comment by ynixt** [comment]
Bank account balance has been removed from listing as this automatic update would be heavy to the server because the way it is currently implemented.
